# This is a basic workflow
name: build

# Controls when the action will run.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v5
    
    # Compile tex files
    - name: Compile files
      uses: xu-cheng/latex-action@v4
      with:
        root_file: document.tex
    
    # Upload thesis
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: thesis
        path: document.pdf

    # Upload logs
    - name: Upload logs
      if: failure() && !cancelled()
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: document.log
